# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48e652e0cace88c09f640e5c40405cbead7a6f966b848eb2f55730255288396dd40f17fbf6d52a5137385c279fb8d6ee34ed772516dd1aa8d096ac2ea4672fc3

test:
  secret_key_base: d8819f9b4bde83b8bdf8de1a46d923ba70cac079c77659a24948a48d9bcd3977dc353f92d4d68a1acb1ed06513fd484014513cf28918f25e1d137d163262521d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
